version: "3.7"
services:
  service:
    build: service
    image: harbor.adorsys.de/psd2-sandbox/sandbox
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/consent
    depends_on:
      - db
  db:
    image: centos/postgresql-10-centos7
    environment:
      - POSTGRESQL_USER=cms
      - POSTGRESQL_PASSWORD=cms
      - POSTGRESQL_DATABASE=consent
    ports:
      - "5432:5432"
  ssl-proxy:
    build: ssl-proxy
    image: harbor.adorsys.de/psd2-sandbox/ssl-proxy
    environment:
      - API_INTERNAL_URL=${API_INTERNAL_URL:-http://service:8080}
      - API_EXTERNAL_URL=${API_EXTERNAL_URL:-api.sandbox.vcap.me}
      - PORTAL_INTERNAL_URL=${PORTAL_INTERNAL_URL:-http://service:8081}
      - PORTAL_EXTERNAL_URL=${PORTAL_EXTERNAL_URL:-portal.sandbox.vcap.me}
    ports:
      - "8443:8443"
    depends_on:
      - service
