apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
  labels:
    app: psd2-sandbox
  name: psd2-sandbox
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: psd2-sandbox
    deploymentconfig: psd2-sandbox
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
      labels:
        app: psd2-sandbox
        deploymentconfig: psd2-sandbox
    spec:
      containers:
      - env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://db/consent
        - name: SPRING_PROFILES_ACTIVE
          value: test
      - image: " "
        imagePullPolicy: Always
        name: psd2-sandbox
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: 768M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - psd2-sandbox
      from:
        kind: ImageStreamTag
        name: psd2-sandbox:ci
        namespace: psd2-sandbox-dev
    type: ImageChange
